changes to comment and cleaning unwanted
petermugabo250/My-First-Blog-apis pull request #7
Opened 2023-10-19 15:02 UTC by petermugabo250

hello check me

2023-10-19 15:24 UTC, muhozajohn approved these changes

2023-10-19 15:24 UTC, muhozajohn commented on src/controller/blogcontroller.js
> -// use agrgregate to retrieve Data
Remove this Comment

2023-10-19 15:24 UTC, muhozajohn approved these changes

2023-10-19 16:02 UTC, mansurissa requested changes
Go back in your whole project and rename`blog` to `post`, user camelCase for all of your varaible names and file names, and make sure your response has : status, message, data/error and work on the rest of the comments I left while reviewing. Happy hacking

2023-10-19 16:02 UTC, mansurissa commented on src/controller/blogcontroller.js
> +    const post = await blogmode.findById(id);
REname this to blog blogModel (Use camelCase please)

2023-10-19 16:02 UTC, mansurissa commented on src/controller/blogcontroller.js
>        user: usertable._id,
use camelCase so userTable

2023-10-19 16:02 UTC, mansurissa commented on src/controller/blogcontroller.js
>  export const allBlogs = async (req, res) => {
rename this to something like getAllPosts

2023-10-19 16:02 UTC, mansurissa commented on src/controller/blogcontroller.js
>        data: gettaallinfo,
Use an understandable variable names

2023-10-19 16:02 UTC, mansurissa commented on src/controller/blogcontroller.js
> +      username: usertable.lastname,
It seems like `usertable` is the loggedn in user, go back in your authentication middleware and rename it to something like `loggedInUser` or `authenticatedUser`.

2023-10-19 20:38 UTC, muhozajohn requested changes

2023-10-19 20:38 UTC, muhozajohn commented on src/controller/blogcontroller.js
> -      message: "Your Blog have been created",
add status code

2023-10-19 20:38 UTC, muhozajohn commented on src/controller/blogcontroller.js
> +      statusbar: "500",
use status not statusbar

2023-10-19 20:38 UTC, muhozajohn commented on src/controller/blogcontroller.js
>      console.log(error.message)
add return function on catch that will cath errors and stutas code

2023-10-19 20:38 UTC, muhozajohn commented on src/controller/blogcontroller.js
> +//getting allPosts
Remove this Comment

2023-10-19 20:38 UTC, muhozajohn commented on src/controller/blogcontroller.js
> +// Deleting Post By Id
Remove this comment

2023-10-19 20:38 UTC, muhozajohn commented on src/controller/userControllers.js
> +      statusbar: "500",
change to status

2023-10-20 12:47 UTC, muhozajohn approved these changes

2023-10-20 12:48 UTC, merged